### PR TITLE
Fixed blank screen issue and misc errors

### PR DESCRIPTION
**Pull request by Nirzak**
Fixed an issue where the torrent list screen completely shows blank.

Fixed misc errors on console screen.

### CODE REVIEW

**Comment by Nirzak** [comment]
This pull request will fix issue #37 #35 #34

**Comment by Nirzak** [comment]
> Fixed an issue where the torrent list screen completely shows blank.
> 
> Fixed misc errors on console screen.

@xombiemp review on your free time please!

**Comment by xombiemp** [comment]
@Nirzak Remove the label modification and I will merge this

**Comment by Nirzak** [comment]
> @Nirzak Remove the label modification and I will merge this

@xombiemp I have rechecked. the main issue was in labels panel. that's why the screen was not appearing. in fact I have re-edit and checked. Again the type error occurred. Following are the valid labels of latest rutorrent

image

so as there's only two labels with l in the middle dls and nlb and nlb already exists so I have replaced the other one with dls.

**Comment by Nirzak** [comment]
or I have seen that if we remove .cnt from `theWebUI.labels['-_-_-' + l + '-_-_-'].cnt` then also the plugin works. but in both ways particular torrent count of labels don't appears. 
So found solutions:
Either we can use:
`theWebUI.labels['-_-_-' + l + '-_-_-']`

or
`theWebUI.labels['-_-_-dls-_-_-'].cnt`

and the type error is this one if we use the previous label with cnt
```
Uncaught TypeError: Cannot read properties of undefined (reading 'cnt') from TypeError: Cannot read properties of undefined (reading 'cnt')
    at <anonymous>:9123:180
    at Array.forEach (<anonymous>)
    at <anonymous>:9118:39
    at Object.<anonymous> (https://removedurl/rutorrent/js/rtorrent.js?v=422:1297:8)
    at c (https://
```

**Comment by xombiemp** [comment]
This was fixed with https://github.com/xombiemp/rutorrentMobile/commit/be00f6cd8bd9d1dd9be9c743fb959d4d5657f37f

**Pull request closed without merging**
